import {
  CalendarDays,
  ListTodo,
  EyeOff,
  Trash2,
  X,
  StickyNote,
  Truck,
  CalendarCheck,
  RotateCcw,
  Info,
  CalendarPlus,
  ChevronDown,
  Plus,
  Loader2,
  PenLine,
  Upload,
  Plug,
  Circle,
  Clock,
  AlertTriangle,
  Calendar,
  CalendarX,
  Car,
  UserX,
  Users,
  FileSignature,
  MessageCircle,
  ClipboardCheck,
  Archive,
  ArrowLeft,
  Phone,
  ClipboardList,
  Mail,
  MessageSquare,
  UserCheck,
  MoreVertical,
  Filter,
  Paperclip,
  ExternalLink,
  FolderOpen,
  Tag,
  FileText,
  CheckCircle,
  Search,
  Check,
  Printer,
  Download,
  Send,
  Warehouse,
  Settings,
  User,
  ChevronRight,
  Inbox,
  Lightbulb,
  Sparkles,
  ChevronLeft,
  Handshake,
  ShoppingCart,
  CreditCard,
  FileCheck,
  UserCircle,
  UserPlus,
  Briefcase,
  LineChart,
  ArrowDownWideNarrow,
  MapPin,
  List,
  Zap,
  Pin,
  Link,
  ArrowUp,
  ArrowDown,
  Ban,
  Copy,
  PlusCircle,
  ListChecks,
  Minus,
  Building2,
  BadgeCheck,
  Square,
  Mic,
  ChevronUp
} from 'lucide-vue-next'

const faToLucide = {
  'fa-solid fa-calendar-day': CalendarDays,
  'fa-regular fa-calendar': Calendar,
  'fa-solid fa-calendar': Calendar,
  'fa-solid fa-tasks': ListTodo,
  'fa-solid fa-eye-slash': EyeOff,
  'fa-solid fa-trash': Trash2,
  'fa-solid fa-x': X,
  'fa-solid fa-xmark': X,
  'fa-solid fa-sticky-note': StickyNote,
  'fa-solid fa-truck': Truck,
  'fa-solid fa-calendar-check': CalendarCheck,
  'fa-regular fa-calendar-check': CalendarCheck,
  'fa-solid fa-rotate-left': RotateCcw,
  'fa-solid fa-info-circle': Info,
  'fa-solid fa-calendar-plus': CalendarPlus,
  'fa-solid fa-chevron-down': ChevronDown,
  'fa-solid fa-plus': Plus,
  'fa-solid fa-spinner': Loader2,
  'fa-solid fa-pen': PenLine,
  'fa-solid fa-upload': Upload,
  'fa-solid fa-plug': Plug,
  'fa-solid fa-circle': Circle,
  'fa-solid fa-clock': Clock,
  'fa-solid fa-exclamation-triangle': AlertTriangle,
  'fa-solid fa-calendar-days': CalendarDays,
  'fa-solid fa-calendar-xmark': CalendarX,
  'fa-solid fa-car': Car,
  'fa-solid fa-user-slash': UserX,
  'fa-solid fa-user-group': Users,
  'fa-solid fa-file-invoice-dollar': FileSignature,
  'fa-solid fa-file-signature': FileSignature,
  'fa-solid fa-comment': MessageCircle,
  'fa-solid fa-clipboard-check': ClipboardCheck,
  'fa-solid fa-archive': Archive,
  'fa-solid fa-arrow-left': ArrowLeft,
  'fa-solid fa-phone': Phone,
  'fa-solid fa-phone-volume': Phone,
  'fa-solid fa-clipboard-list': ClipboardList,
  'fa-solid fa-message': MessageSquare,
  'fa-solid fa-envelope': Mail,
  'fa-regular fa-envelope': Mail,
  'fa-solid fa-user-check': UserCheck,
  'fa-solid fa-ellipsis-vertical': MoreVertical,
  'fa-solid fa-filter': Filter,
  'fa-solid fa-paperclip': Paperclip,
  'fa-solid fa-external-link': ExternalLink,
  'fa-solid fa-folder-open': FolderOpen,
  'fa-solid fa-comments': MessageCircle,
  'fa-solid fa-tag': Tag,
  'fa-solid fa-file-invoice': FileText,
  'fa-solid fa-file-contract': FileCheck,
  'fa-solid fa-check-circle': CheckCircle,
  'fa-solid fa-search': Search,
  'fa-solid fa-check': Check,
  'fa-solid fa-print': Printer,
  'fa-solid fa-download': Download,
  'fa-solid fa-paper-plane': Send,
  'fa-solid fa-exclamation-circle': AlertTriangle,
  'fa-solid fa-warehouse': Warehouse,
  'fa-solid fa-cog': Settings,
  'fa-solid fa-pen-to-square': PenLine,
  'fa-solid fa-user-circle': UserCircle,
  'fa-solid fa-chevron-right': ChevronRight,
  'fa-solid fa-inbox': Inbox,
  'fa-solid fa-lightbulb': Lightbulb,
  'fa-solid fa-sparkles': Sparkles,
  'fa-solid fa-chevron-left': ChevronLeft,
  'fa-solid fa-user': User,
  'fa-solid fa-note-sticky': StickyNote,
  'fa-regular fa-note-sticky': StickyNote,
  'fa-solid fa-comment-dots': MessageCircle,
  'fa-solid fa-car-side': Car,
  'fa-solid fa-handshake': Handshake,
  'fa-solid fa-shopping-cart': ShoppingCart,
  'fa-solid fa-credit-card': CreditCard,
  'fa-solid fa-users': Users,
  'fa-solid fa-user-plus': UserPlus,
  'fa-solid fa-briefcase': Briefcase,
  'fa-solid fa-road': Car,
  'fa-solid fa-id-card': UserCircle,
  'fa-brands fa-whatsapp': MessageCircle,
  'fa-brands fa-volkswagen': Car,
  'fa-solid fa-chart-line': LineChart,
  'fa-solid fa-arrow-down-wide-short': ArrowDownWideNarrow,
  'fa-solid fa-location-dot': MapPin,
  'fa-solid fa-list': List,
  'fa-regular fa-clock': Clock,
  'fa-solid fa-bolt': Zap,
  'fa-solid fa-thumbtack': Pin,
  'fa-solid fa-link': Link,
  'fa-solid fa-arrow-up': ArrowUp,
  'fa-solid fa-arrow-down': ArrowDown,
  'fa-solid fa-ban': Ban,
  'fa-solid fa-copy': Copy,
  'fa-solid fa-plus-circle': PlusCircle,
  'fa-solid fa-list-check': ListChecks,
  'fa-solid fa-minus': Minus,
  'fa-solid fa-building': Building2,
  'fa-regular fa-id-badge': BadgeCheck,
  'fa-solid fa-stop': Square,
  'fa-solid fa-waveform-lines': Mic,
  'fa-solid fa-magnifying-glass': Search,
  'fa-solid fa-times-circle': X,
  'fa-regular fa-trash-can': Trash2,
  'fa-regular fa-pen-to-square': PenLine,
  'fa-solid fa-fire': Zap,
  'fa-solid fa-cloud-arrow-up': Upload
}

export function getLucideIcon(faClassString) {
  if (!faClassString || typeof faClassString !== 'string') {
    return Circle
  }
  const parts = faClassString.trim().split(/\s+/)
  const key = parts.length >= 2 ? `${parts[0]} ${parts[1]}` : parts[0].startsWith('fa-') ? `fa-solid ${parts[0]}` : parts[0]
  return faToLucide[key] || Circle
}
